GET http://um.novasquare.vn:8080/abc

### Register User

POST http://um.novasquare.vn:8080/api/v1/auth/register
Content-Type: application/json

{
    "username":"quang.hoang",
    "EMAIL":"quang.hoang@novasquare.vn",
    "password":"123456",
    "FIRST_NAME":"Quang",
    "LAST_NAME":"Hoang Nhat",
    "PRIMARY_PHONE":"0973617933"
}

### Login

POST http://um.novasquare.vn:8080/api/v1/auth/login
Content-Type: application/json

{
    "username":"quang.hoang",
    "password":"123456"
}

### Logout

GET http://um.novasquare.vn:8080/api/v1/auth/logout


### Refresh Token

GET http://um.novasquare.vn:8080/api/v1/auth/refresh_token

